### PR TITLE
Login

### PR DESCRIPTION
**Pull request by agnes97**
- Add Login page and component
- Add ForgottenPassword component
- Add toggle eye to Login component

### CODE REVIEW

**Comment by MartinaVilimova** [comment]
Maybe I would just increase the width of the inputs. Now I wrote an email that my parents and Tom have and took up the full breadth of input. So I would probably increase the width, there is enough space on the page.
image
image

Just my opinion. otherwise I didn't notice anything.

**Comment by agnes97** [comment]
> Maybe I would just increase the width of the inputs. Now I wrote an email that my parents and Tom have and took up the full breadth of input. So I would probably increase the width, there is enough space on the page.
> image
> image
> 
> Just my opinion. otherwise I didn't notice anything.

I'm working on this! It's a really good point but it's way harder to fix then I imagined! I already re-designed the whole Form component to work as a grid, but not it's broken for mobile and the eye toggle doesn't work even on desktop. I'm gonna try to make it work tommorow!
pain
pain2

**Comment by agnes97** [comment]
Done! <3 
image_2021-02-12_140429

**Comment by MartinaVilimova** [comment]
Great 👍 

I would still change the button. Since we already have one universal, I would also use it in the form. He just has to adjust a little.
image
add name and type to component Button -> index.tsx

image
add StyledButton to component Form -> styled.ts

image
image

edit the entry on the form 

...and then the button should look just like yours 👍 

PS: The text of the button will be big, but I've already fixed it in my branch on the profile refactor, so then just rewrite the title to titleSmall, now you're not solving it 🙂

**Pull request merged**
